services:
  web:
    build: .
    expose:
      - "8001"
    env_file:
      - .env
    volumes:
      - littlelemon_static:/app/staticfiles
    restart: always
    networks:
      - shared

volumes:
  littlelemon_static:
    external: true

networks:
  shared:
    external: true
    name: shared_network